export const CIS_GEO = {
  countries: [
    { id: 'uz', nameRu: 'Узбекистан', nameEn: 'Uzbekistan', currency: 'UZS', currencyLabelRu: 'сум', currencyLabelEn: 'som', sortOrder: 1 },
    { id: 'kz', nameRu: 'Казахстан', nameEn: 'Kazakhstan', currency: 'KZT', currencyLabelRu: '₸', currencyLabelEn: '₸', sortOrder: 2 },
    { id: 'kg', nameRu: 'Кыргызстан', nameEn: 'Kyrgyzstan', currency: 'KGS', currencyLabelRu: 'сом', currencyLabelEn: 'som', sortOrder: 3 },
    { id: 'tj', nameRu: 'Таджикистан', nameEn: 'Tajikistan', currency: 'TJS', currencyLabelRu: 'сомони', currencyLabelEn: 'somoni', sortOrder: 4 },
    { id: 'tm', nameRu: 'Туркменистан', nameEn: 'Turkmenistan', currency: 'TMT', currencyLabelRu: 'манат', currencyLabelEn: 'manat', sortOrder: 5 },
    { id: 'am', nameRu: 'Армения', nameEn: 'Armenia', currency: 'AMD', currencyLabelRu: '֏', currencyLabelEn: '֏', sortOrder: 6 },
    { id: 'az', nameRu: 'Азербайджан', nameEn: 'Azerbaijan', currency: 'AZN', currencyLabelRu: '₼', currencyLabelEn: '₼', sortOrder: 7 },
    { id: 'by', nameRu: 'Беларусь', nameEn: 'Belarus', currency: 'BYN', currencyLabelRu: 'Br', currencyLabelEn: 'Br', sortOrder: 8 },
    { id: 'md', nameRu: 'Молдова', nameEn: 'Moldova', currency: 'MDL', currencyLabelRu: 'лей', currencyLabelEn: 'lei', sortOrder: 9 },
    { id: 'ru', nameRu: 'Россия', nameEn: 'Russia', currency: 'RUB', currencyLabelRu: '₽', currencyLabelEn: '₽', sortOrder: 10 },
  ],
  cities: [
    { id: 'tashkent', countryId: 'uz', nameRu: 'Ташкент', nameEn: 'Tashkent' },
    { id: 'samarkand', countryId: 'uz', nameRu: 'Самарканд', nameEn: 'Samarkand' },
    { id: 'almaty', countryId: 'kz', nameRu: 'Алматы', nameEn: 'Almaty' },
    { id: 'astana', countryId: 'kz', nameRu: 'Астана', nameEn: 'Astana' },
    { id: 'bishkek', countryId: 'kg', nameRu: 'Бишкек', nameEn: 'Bishkek' },
    { id: 'dushanbe', countryId: 'tj', nameRu: 'Душанбе', nameEn: 'Dushanbe' },
    { id: 'ashgabat', countryId: 'tm', nameRu: 'Ашхабад', nameEn: 'Ashgabat' },
    { id: 'yerevan', countryId: 'am', nameRu: 'Ереван', nameEn: 'Yerevan' },
    { id: 'baku', countryId: 'az', nameRu: 'Баку', nameEn: 'Baku' },
    { id: 'minsk', countryId: 'by', nameRu: 'Минск', nameEn: 'Minsk' },
    { id: 'chisinau', countryId: 'md', nameRu: 'Кишинёв', nameEn: 'Chisinau' },
    { id: 'kazan', countryId: 'ru', nameRu: 'Казань', nameEn: 'Kazan' },
    { id: 'yekaterinburg', countryId: 'ru', nameRu: 'Екатеринбург', nameEn: 'Yekaterinburg' },
  ],
  districts: [
    { id: 'yunusabad', cityId: 'tashkent', nameRu: 'Юнусабад', nameEn: 'Yunusabad' },
    { id: 'chilanzar', cityId: 'tashkent', nameRu: 'Чиланзар', nameEn: 'Chilanzar' },
    { id: 'mirzo', cityId: 'tashkent', nameRu: 'Мирзо-Улугбек', nameEn: 'Mirzo-Ulugbek' },
    { id: 'sergeli', cityId: 'tashkent', nameRu: 'Сергели', nameEn: 'Sergeli' },
    { id: 'siab', cityId: 'samarkand', nameRu: 'Сиаб', nameEn: 'Siab' },
    { id: 'sam-center', cityId: 'samarkand', nameRu: 'Центр', nameEn: 'Center' },
    { id: 'almaly', cityId: 'almaty', nameRu: 'Алмалы', nameEn: 'Almaly' },
    { id: 'bostandyk', cityId: 'almaty', nameRu: 'Бостандык', nameEn: 'Bostandyk' },
    { id: 'esil', cityId: 'astana', nameRu: 'Есиль', nameEn: 'Esil' },
    { id: 'astana-almaty', cityId: 'astana', nameRu: 'Алматы', nameEn: 'Almaty' },
    { id: 'oktyabr', cityId: 'bishkek', nameRu: 'Октябрьский', nameEn: 'Oktyabrsky' },
    { id: 'lenin', cityId: 'bishkek', nameRu: 'Ленинский', nameEn: 'Leninsky' },
    { id: 'sino', cityId: 'dushanbe', nameRu: 'Сино', nameEn: 'Sino' },
    { id: 'firdavsi', cityId: 'dushanbe', nameRu: 'Фирдавси', nameEn: 'Firdavsi' },
    { id: 'kopetdag', cityId: 'ashgabat', nameRu: 'Копетдаг', nameEn: 'Kopetdag' },
    { id: 'berkararlyk', cityId: 'ashgabat', nameRu: 'Беркарарлык', nameEn: 'Berkararlyk' },
    { id: 'kentron', cityId: 'yerevan', nameRu: 'Кентрон', nameEn: 'Kentron' },
    { id: 'arabkir', cityId: 'yerevan', nameRu: 'Арабкир', nameEn: 'Arabkir' },
    { id: 'yasamal', cityId: 'baku', nameRu: 'Ясамал', nameEn: 'Yasamal' },
    { id: 'nasimi', cityId: 'baku', nameRu: 'Насими', nameEn: 'Nasimi' },
    { id: 'tsentralny', cityId: 'minsk', nameRu: 'Центральный', nameEn: 'Tsentralny' },
    { id: 'sovetsky', cityId: 'minsk', nameRu: 'Советский', nameEn: 'Sovetsky' },
    { id: 'centru', cityId: 'chisinau', nameRu: 'Центр', nameEn: 'Centru' },
    { id: 'botanica', cityId: 'chisinau', nameRu: 'Ботаника', nameEn: 'Botanica' },
    { id: 'vakhitovsky', cityId: 'kazan', nameRu: 'Вахитовский', nameEn: 'Vakhitovsky' },
    { id: 'kazan-sovetsky', cityId: 'kazan', nameRu: 'Советский', nameEn: 'Sovetsky' },
    { id: 'ekb-leninsky', cityId: 'yekaterinburg', nameRu: 'Ленинский', nameEn: 'Leninsky' },
    { id: 'ekb-kirovsky', cityId: 'yekaterinburg', nameRu: 'Кировский', nameEn: 'Kirovsky' },
  ],
};

export const SLOTS = ['10:00–12:00', '12:00–14:00', '16:00–18:00'];
