export const en = {
  brand: 'JOL-Ashkana',
  slogan: 'Home baking for tomorrow. Don’t hunt chats — order in the app.',
  subline: 'Menu, price and a pickup slot — no chats. Cash on handover only.',
  ctaDistrict: 'Pick a district and order for tomorrow',
  ctaLogin: 'Log in',
  ctaRegister: 'Create an account',
  iAmBaker: 'I’m a baker',
  iAmBuyer: 'I’m a buyer',
  iAmSupport: 'Support',
  social: 'CIS countries · no card payments, no SMS',
  landHow: 'How',
  landWhy: 'Why',
  landBakers: 'Bakers',
  stepsTitle: 'How to order for tomorrow',
  landHowLead:
    'A guest does not message the baker. They pick a district, see tomorrow’s menu, and place the order in the app. Price, slot and status live on one screen.',
  steps: [
    {
      n: '1',
      t: 'District',
      d: 'Country → city → district. Kitchens nearby, not the whole city. Without a district the catalog stays empty.',
    },
    {
      n: '2',
      t: 'Tomorrow’s menu',
      d: 'Price, ingredients, leftover and cutoff are visible at once. No “how much?” and no waiting for a reply.',
    },
    {
      n: '3',
      t: 'Status',
      d: 'Accepted → baking → ready → handed over. Guest and baker see the same thing. Cash on handover only.',
    },
  ],
  vsTitle: 'Why this, not a chat',
  landWhyLead:
    'People still hunt homemade baking in Telegram and Instagram. There is no price, slot or status — only a thread. JOL puts the order in one place, without a marketplace cut.',
  landWhyNow: 'Now',
  landWhyJol: 'In JOL',
  vsPoints: [
    { bad: 'Telegram: chaos in the thread, price and slot get lost', good: 'One menu for the day: price, ingredients and slot up front' },
    { bad: 'Instagram: pretty, but you cannot order', good: 'Cart, time slot and live order status in the app' },
    { bad: 'Delivery apps: 25–35% commission from the kitchen', good: 'No commission in this version. Cash on handover' },
  ],
  landBakersTitle: 'Bakers — same account',
  landBakersLead:
    'No second signup. The same person can buy and bake. A kitchen shows in the district only after support verifies it.',
  landBakersBody:
    'Send the name, full name, full address and district. Confirm you cook there. After review, put tomorrow’s menu up: photo or emoji, price, leftover. Orders land in the cabinet — you move the status, the guest sees it without a chat.',
  bakerPath: [
    { n: '01', t: 'Apply', d: 'Kitchen, address, district, cutoff hour. Support checks it is a real kitchen.' },
    { n: '02', t: 'Menu', d: 'Dishes for tomorrow: price, ingredients, photo or icon, how many portions left.' },
    { n: '03', t: 'Orders', d: 'Accepted → baking → ready → handed over. The guest sees the same status.' },
  ],
  addToCart: 'Add',
  photoLabel: 'Photo',
  photoHint: 'JPG, PNG or WebP. We shrink it automatically.',
  photoRemove: 'Remove photo',
  photoError: 'Photo is too large or not an image.',
  pickEmoji: 'Icon',
  navHome: 'Home',
  navDistrict: 'District',
  navCart: 'Cart',
  navOrders: 'Orders',
  navBaker: 'Baker',
  navAccount: 'Account',
  pickDistrictFirst: 'Pick a country, city and district first',
  emptyDistrict: 'No kitchens in this district yet. Be the first baker.',
  beFirstBaker: 'Open a kitchen',
  tomorrowStrip: 'Tomorrow nearby',
  availableStrip: 'On tomorrow’s menu',
  cutoffLate: 'Orders close at {hour}:00. It’s late — this order goes to the day after tomorrow.',
  cutoffOk: 'Orders until {hour}:00',
  cartOtherBaker: 'Your cart has dishes from another kitchen. Replace?',
  replace: 'Replace',
  keep: 'Keep',
  added: 'Added to cart',
  cartEmpty: 'Cart is empty. Pick a district and add dishes for tomorrow.',
  checkout: 'Checkout',
  orderTomorrow: 'Order for tomorrow',
  payCash: 'Pay cash on pickup or to the courier. No cards.',
  needLogin: 'Log in to place an order.',
  phoneError: 'Enter a phone number — at least 9 digits.',
  addressError: 'Courier needs an address.',
  nameError: 'What should we call you?',
  orderPlaced: 'Order placed',
  leftoverFew: 'Few left',
  leftoverOut: 'Sold out for tomorrow',
  pickup: 'Pickup',
  courier: 'Courier',
  slot: 'Slot',
  name: 'Name',
  phone: 'Phone',
  address: 'Address',
  comment: 'Comment',
  email: 'Email',
  password: 'Password',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  myOrdersEmpty: 'No orders yet. The first one takes a couple of minutes.',
  trackHint: 'The baker updates status. Open the order to see accepted, baking, ready, handed over.',
  cabinetTitle: 'Baker cabinet',
  tabOrders: 'Orders',
  tabMenu: 'Menu',
  tabKitchen: 'Kitchen',
  noOrdersToday: 'No orders for tomorrow yet.',
  myKitchen: 'My kitchen',
  createKitchen: 'Submit kitchen for review',
  createKitchenHint: 'Name, address and district. Support confirms it is a real kitchen — then guests can see you.',
  kitchenName: 'Kitchen name',
  ownerFullName: 'Owner full name',
  kitchenBio: 'About you',
  kitchenAddress: 'Full address',
  cutoffHour: 'Cutoff hour',
  kitchenSaved: 'Sent for review',
  confirmCooks: 'I cook at this address. This is a real kitchen.',
  addDish: 'Add a dish',
  dishName: 'Dish',
  dishPrice: 'Price',
  dishUnit: 'Unit',
  dishCategory: 'Category',
  dishIngredients: 'Ingredients',
  dishAdded: 'Dish is on tomorrow’s menu',
  guest: 'Guest',
  baker: 'Baker',
  buyer: 'Buyer',
  country: 'Country',
  city: 'City',
  district: 'District',
  ingredients: 'Ingredients',
  qty: 'Qty',
  total: 'Total',
  delivery: 'Handover',
  confirm: 'Place order',
  cancel: 'Cancel',
  status: {
    accepted: 'Accepted',
    baking: 'Baking',
    ready: 'Ready',
    delivered: 'Handed over',
    cancelled: 'Cancelled',
  },
  ticketStatus: {
    open: 'New',
    working: 'In progress',
    closed: 'Closed',
  },
  filterAll: 'All',
  leftover: 'Left',
  statOpen: 'Open',
  yourOrder: 'Your order',
  onMenu: 'Tomorrow',
  offMenu: 'Hidden',
  adminTitle: 'Support',
  adminHello: 'Orders, kitchens, reports, blocks',
  adminSub: 'Staff only. A hidden or unverified kitchen does not show in the district.',
  adminKitchens: 'Kitchens',
  adminOrders: 'Orders',
  adminTickets: 'Reports',
  adminUsers: 'People',
  adminSearch: 'Find an order',
  adminSearchHint: 'Phone, name or order id',
  adminNoOrders: 'Nothing found.',
  adminForceCancel: 'Cancel order',
  adminHide: 'Hide',
  adminShow: 'Show',
  adminVerify: 'Verify',
  adminReject: 'Reject',
  adminBlock: 'Block',
  adminUnblock: 'Unblock',
  kitchenHidden: 'Kitchen is hidden',
  kitchenHiddenHint: 'Support took this kitchen off the list. Pick another in the district.',
  kitchenPending: 'Kitchen is under review. It is not visible in the district yet.',
  kitchenRejected: 'Application rejected',
  loginTitle: 'Log in',
  registerTitle: 'Create account',
  loginHint: 'Email and password. No SMS.',
  registerHint: 'One account: buyer and baker.',
  noAccount: 'No account? Register',
  hasAccount: 'Already have an account? Log in',
  logout: 'Log out',
  accountTitle: 'Account',
  roleSwitch: 'Mode',
  roleSwitchHint: 'One account. Buy as a guest or cook as a baker.',
  blockedTitle: 'Account blocked',
  report: 'Report',
  reportTitle: 'Report to support',
  reportHint: 'Describe the problem. Support can hide a kitchen or block a person.',
  reportSent: 'Report sent',
  reportBody: 'What happened',
  topic: 'Topic',
  topics: {
    late: 'Late',
    quality: 'Food quality',
    fake_kitchen: 'Fake kitchen',
    rude: 'Rude',
    other: 'Other',
  },
  save: 'Save',
  language: 'Language',
  authError: 'Wrong email or password',
  existsError: 'This email is already registered',
  loginNotFoundError: 'Wrong email or password',
  loginPasswordError: 'Wrong email or password',
  passwordHint: 'At least 8 characters',
  emailError: 'Check the email — use name@mail.com',
  dbError: 'Database is not connected. On Vercel add DATABASE_URL (Neon) and Redeploy.',
  serverError: 'The API crashed. Push this code, set JWT_SECRET, Redeploy, then register on the live site.',
  apiMissingError: 'API route missing. Redeploy the project.',
  networkError: 'No connection to the server.',
  healthBanner: 'Database is down. {hint}',
  nextStatus: 'Next status',
  verifyHint: 'Check the address and name, then verify the kitchen.',
  rejectNote: 'Rejection reason',
  blockReason: 'Block reason',
  blockReasonRequired: 'Write a block reason first.',
  pendingShort: 'Pending',
  verifiedShort: 'Verified',
  rejectedShort: 'Rejected',
  hiddenShort: 'Hidden',
  tomorrow: 'tomorrow',
  dayAfter: 'the day after tomorrow',
  adminVerified: 'Kitchen verified',
  adminRejected: 'Kitchen rejected',
  adminHidden: 'Kitchen hidden from the district',
  adminShown: 'Kitchen is visible again',
  adminBlocked: 'User blocked',
  adminUnblocked: 'User unblocked',
  adminCancelled: 'Order cancelled',
  adminTicketUpdated: 'Report status updated',
  adminActionFailed: 'That didn’t work. Try again.',
  adminFieldsError: 'Fill in the required fields.',
  adminEmptyKitchens: 'No kitchen applications yet.',
  adminEmptyUsers: 'No users yet.',
  adminEmptyTickets: 'No reports yet.',
  adminOrdersHint: 'New orders start as accepted. The baker moves them on. Support can only cancel.',
};
