export const ru = {
  brand: 'JOL-Ashkana',
  slogan: 'Домашняя выпечка завтра. Не ищи в чатах — закажи в приложении.',
  subline: 'Меню, цена и слот — без чатов. Оплата наличными при получении.',
  ctaDistrict: 'Выбери район и закажи на завтра',
  ctaLogin: 'Войти',
  ctaRegister: 'Создать аккаунт',
  iAmBaker: 'Я пекарь',
  iAmBuyer: 'Я покупатель',
  iAmSupport: 'Поддержка',
  social: 'Страны СНГ · без оплаты картой и без SMS',
  stepsTitle: 'Как это работает',
  steps: [
    { n: '1', t: 'Район', d: 'Страна, город и район — кухни рядом, а не весь город.' },
    { n: '2', t: 'Меню на завтра', d: 'Цена, состав и слот видны сразу. Без «сколько стоит?» в чате.' },
    { n: '3', t: 'Статус', d: 'Принят → печётся → готово → выдано. Ты и пекарь видите одно и то же.' },
  ],
  vsTitle: 'Не Telegram и не Яндекс',
  vsPoints: [
    { bad: 'Telegram: хаос в переписке', good: 'JOL: одно меню на день' },
    { bad: 'Instagram: красиво, но заказать нельзя', good: 'JOL: корзина и слот' },
    { bad: 'Доставка: комиссия 25–35%', good: 'JOL: без комиссии в этой версии' },
  ],
  navHome: 'Главная',
  navDistrict: 'Район',
  navCart: 'Корзина',
  navOrders: 'Заказы',
  navBaker: 'Пекарь',
  navAccount: 'Аккаунт',
  pickDistrictFirst: 'Сначала выбери страну, город и район',
  emptyDistrict: 'В этом районе пока нет кухонь. Станьте первым пекарем.',
  beFirstBaker: 'Открыть кухню',
  cutoffLate: 'Приём заказов до {hour}:00. Сейчас уже поздно — заказ уйдёт на послезавтра.',
  cutoffOk: 'Приём до {hour}:00',
  cartOtherBaker: 'В корзине блюда другой кухни. Заменить?',
  replace: 'Заменить',
  keep: 'Оставить',
  added: 'Добавлено в корзину',
  cartEmpty: 'Корзина пустая. Выбери район и добавь блюда на завтра.',
  checkout: 'К оформлению',
  orderTomorrow: 'Заказать на завтра',
  payCash: 'Оплата наличными при получении. Карт и онлайн-платежей нет.',
  needLogin: 'Чтобы заказать, войдите в аккаунт.',
  phoneError: 'Введите телефон — не меньше 9 цифр.',
  addressError: 'Для курьера нужен адрес.',
  nameError: 'Как к вам обращаться?',
  orderPlaced: 'Заказ оформлен',
  leftoverFew: 'Осталось мало',
  leftoverOut: 'На завтра уже нет',
  pickup: 'Самовывоз',
  courier: 'Курьер',
  slot: 'Слот',
  name: 'Имя',
  phone: 'Телефон',
  address: 'Адрес',
  comment: 'Комментарий',
  email: 'Email',
  password: 'Пароль',
  showPassword: 'Показать пароль',
  hidePassword: 'Скрыть пароль',
  myOrdersEmpty: 'Заказов пока нет. Первый можно собрать за пару минут.',
  trackHint: 'Статус меняет пекарь. Откройте заказ — увидите: принят, печётся, готово, выдано.',
  cabinetTitle: 'Кабинет пекаря',
  tabOrders: 'Заказы',
  tabMenu: 'Меню',
  tabKitchen: 'Кухня',
  noOrdersToday: 'На завтра заказов ещё нет.',
  myKitchen: 'Моя кухня',
  createKitchen: 'Заявить кухню на проверку',
  createKitchenHint: 'Имя, адрес и район. Поддержка подтвердит, что кухня настоящая — после этого вас увидят гости.',
  kitchenName: 'Название кухни',
  ownerFullName: 'ФИО владельца',
  kitchenBio: 'О себе',
  kitchenAddress: 'Полный адрес',
  cutoffHour: 'Приём до, час',
  kitchenSaved: 'Заявка отправлена на проверку',
  confirmCooks: 'Готовлю по этому адресу, кухня настоящая',
  addDish: 'Добавить блюдо',
  dishName: 'Блюдо',
  dishPrice: 'Цена',
  dishUnit: 'Ед.',
  dishCategory: 'Категория',
  dishIngredients: 'Состав',
  dishAdded: 'Блюдо в меню на завтра',
  guest: 'Гость',
  baker: 'Пекарь',
  buyer: 'Покупатель',
  country: 'Страна',
  city: 'Город',
  district: 'Район',
  ingredients: 'Состав',
  qty: 'Кол-во',
  total: 'Итого',
  delivery: 'Получение',
  confirm: 'Подтвердить заказ',
  cancel: 'Отменить',
  status: {
    accepted: 'Принят',
    baking: 'Печётся',
    ready: 'Готово',
    delivered: 'Выдано',
    cancelled: 'Отменён',
  },
  filterAll: 'Все',
  leftover: 'Остаток',
  onMenu: 'На завтра',
  offMenu: 'Скрыто',
  adminTitle: 'Поддержка',
  adminHello: 'Заказы, кухни, жалобы, блокировки',
  adminSub: 'Только сотрудники. Скрытая или неподтверждённая кухня не видна в районе.',
  adminKitchens: 'Кухни',
  adminOrders: 'Заказы',
  adminTickets: 'Жалобы',
  adminUsers: 'Люди',
  adminSearch: 'Найти заказ',
  adminSearchHint: 'Телефон, имя или номер заказа',
  adminNoOrders: 'Ничего не найдено.',
  adminForceCancel: 'Отменить заказ',
  adminHide: 'Скрыть',
  adminShow: 'Показать',
  adminVerify: 'Подтвердить',
  adminReject: 'Отклонить',
  adminBlock: 'Заблокировать',
  adminUnblock: 'Разблокировать',
  kitchenHidden: 'Кухня временно скрыта',
  kitchenHiddenHint: 'Поддержка сняла кухню с витрины. Выберите другую в районе.',
  kitchenPending: 'Кухня на проверке. В районе её пока не видно.',
  kitchenRejected: 'Заявку отклонили',
  ticketStatus: {
    open: 'Новый',
    working: 'В работе',
    closed: 'Закрыт',
  },
  loginTitle: 'Вход',
  registerTitle: 'Регистрация',
  loginHint: 'Email и пароль. SMS нет.',
  registerHint: 'Один аккаунт: покупатель и пекарь.',
  noAccount: 'Нет аккаунта? Зарегистрируйтесь',
  hasAccount: 'Уже есть аккаунт? Войти',
  logout: 'Выйти',
  accountTitle: 'Аккаунт',
  roleSwitch: 'Режим',
  roleSwitchHint: 'Один аккаунт. Покупайте как гость или готовьте как пекарь.',
  blockedTitle: 'Аккаунт заблокирован',
  report: 'Пожаловаться',
  reportTitle: 'Жалоба в поддержку',
  reportHint: 'Опишите проблему. Поддержка может скрыть кухню или заблокировать человека.',
  reportSent: 'Жалоба отправлена',
  reportBody: 'Что случилось',
  topic: 'Тема',
  topics: {
    late: 'Опоздание',
    quality: 'Качество еды',
    fake_kitchen: 'Кухня ненастоящая',
    rude: 'Грубость',
    other: 'Другое',
  },
  save: 'Сохранить',
  language: 'Язык',
  authError: 'Неверный email или пароль',
  existsError: 'Такой email уже зарегистрирован',
  passwordHint: 'Не меньше 8 символов',
  emailError: 'Проверьте email — нужен вид name@mail.com',
  dbError: 'База не подключена. На Vercel нужен DATABASE_URL (Neon).',
  serverError: 'Сервер недоступен. Локально запустите npm run dev.',
  nextStatus: 'Следующий статус',
  verifyHint: 'Проверьте адрес и ФИО, затем подтвердите кухню.',
  rejectNote: 'Причина отказа',
  blockReason: 'Причина блокировки',
  pendingShort: 'На проверке',
  verifiedShort: 'Подтверждена',
  rejectedShort: 'Отклонена',
  hiddenShort: 'Скрыта',
  tomorrow: 'завтра',
  dayAfter: 'послезавтра',
};
