export const ru = {
  brand: 'JOL-Ashkana',
  slogan: 'Домашняя выпечка завтра. Не ищи в чатах — закажи в приложении.',
  subline: 'Меню, цена и слот — без чатов. Оплата наличными при получении.',
  ctaDistrict: 'Выбери район и закажи на завтра',
  ctaLogin: 'Войти',
  ctaRegister: 'Создать аккаунт',
  iAmBaker: 'Я пекарь',
  iAmBuyer: 'Я покупатель',
  iAmSupport: 'Поддержка',
  social: 'Страны СНГ · без оплаты картой и без SMS',
  stepsTitle: 'Как это работает',
  steps: [
    { n: '1', t: 'Район', d: 'Страна, город и район — кухни рядом, а не весь город.' },
    { n: '2', t: 'Меню на завтра', d: 'Цена, состав и слот видны сразу. Без «сколько стоит?» в чате.' },
    { n: '3', t: 'Статус', d: 'Принят → печётся → готово → выдано. Ты и пекарь видите одно и то же.' },
  ],
  vsTitle: 'Не Telegram и не Яндекс',
  vsPoints: [
    { bad: 'Telegram: хаос в переписке', good: 'JOL: одно меню на день' },
    { bad: 'Instagram: красиво, но заказать нельзя', good: 'JOL: корзина и слот' },
    { bad: 'Приложения: комиссия 25–35%', good: 'JOL: в этой версии комиссии нет' },
  ],
  landHow: 'Как',
  landWhy: 'Зачем',
  landBakers: 'Пекари',
  landBakersTitle: 'Открой кухню',
  landBakersBody: 'Тот же аккаунт. Отправь кухню, дождись проверки — и выложи меню на завтра широкой карточкой: фото или эмодзи.',
  addToCart: 'В корзину',
  photoLabel: 'Фото',
  photoHint: 'JPG, PNG или WebP. Мы сами уменьшим файл.',
  photoRemove: 'Убрать фото',
  photoError: 'Фото слишком большое или это не картинка.',
  pickEmoji: 'Иконка',
  navHome: 'Главная',
  navDistrict: 'Район',
  navCart: 'Корзина',
  navOrders: 'Заказы',
  navBaker: 'Пекарь',
  navAccount: 'Кабинет',
  pickDistrictFirst: 'Сначала выбери страну, город и район',
  emptyDistrict: 'В этом районе пока нет кухонь. Стань первым пекарем.',
  beFirstBaker: 'Открыть кухню',
  cutoffLate: 'Приём до {hour}:00. Уже поздно — заказ уйдёт на послезавтра.',
  cutoffOk: 'Приём до {hour}:00',
  cartOtherBaker: 'В корзине блюда другой кухни. Заменить?',
  replace: 'Заменить',
  keep: 'Оставить',
  added: 'Добавлено в корзину',
  cartEmpty: 'Корзина пуста. Выбери район и добавь блюда на завтра.',
  checkout: 'К оформлению',
  orderTomorrow: 'Заказать на завтра',
  payCash: 'Оплата наличными при самовывозе или курьеру. Без карт.',
  needLogin: 'Чтобы заказать, войди в аккаунт.',
  phoneError: 'Введи телефон — не меньше 9 цифр.',
  addressError: 'Для курьера нужен адрес.',
  nameError: 'Как к тебе обращаться?',
  orderPlaced: 'Заказ принят',
  leftoverFew: 'Мало',
  leftoverOut: 'На завтра нет',
  pickup: 'Самовывоз',
  courier: 'Курьер',
  slot: 'Слот',
  name: 'Имя',
  phone: 'Телефон',
  address: 'Адрес',
  comment: 'Комментарий',
  email: 'Почта',
  password: 'Пароль',
  showPassword: 'Показать пароль',
  hidePassword: 'Скрыть пароль',
  myOrdersEmpty: 'Заказов пока нет. Первый займёт пару минут.',
  trackHint: 'Пекарь меняет статус. Открой заказ — увидишь: принят, печётся, готово, выдано.',
  cabinetTitle: 'Кабинет пекаря',
  tabOrders: 'Заказы',
  tabMenu: 'Меню',
  tabKitchen: 'Кухня',
  noOrdersToday: 'На завтра заказов ещё нет.',
  myKitchen: 'Моя кухня',
  createKitchen: 'Отправить кухню на проверку',
  createKitchenHint: 'Имя, адрес и район. Поддержка подтвердит, что кухня настоящая — тогда гости тебя увидят.',
  kitchenName: 'Название кухни',
  ownerFullName: 'ФИО хозяина',
  kitchenBio: 'О себе',
  kitchenAddress: 'Полный адрес',
  cutoffHour: 'Час отсечки',
  kitchenSaved: 'Отправлено на проверку',
  confirmCooks: 'Готовлю по этому адресу. Это настоящая кухня.',
  addDish: 'Добавить блюдо',
  dishName: 'Блюдо',
  dishPrice: 'Цена',
  dishUnit: 'Единица',
  dishCategory: 'Категория',
  dishIngredients: 'Состав',
  dishAdded: 'Блюдо в меню на завтра',
  guest: 'Гость',
  baker: 'Пекарь',
  buyer: 'Покупатель',
  country: 'Страна',
  city: 'Город',
  district: 'Район',
  ingredients: 'Состав',
  qty: 'Кол-во',
  total: 'Итого',
  delivery: 'Получение',
  confirm: 'Оформить заказ',
  cancel: 'Отмена',
  status: {
    accepted: 'Принят',
    baking: 'Печётся',
    ready: 'Готово',
    delivered: 'Выдано',
    cancelled: 'Отменён',
  },
  ticketStatus: {
    open: 'Новый',
    working: 'В работе',
    closed: 'Закрыт',
  },
  filterAll: 'Все',
  leftover: 'Остаток',
  statOpen: 'Открытые',
  yourOrder: 'Твой заказ',
  onMenu: 'Завтра',
  offMenu: 'Скрыто',
  adminTitle: 'Поддержка',
  adminHello: 'Заказы, кухни, жалобы, блокировки',
  adminSub: 'Только для сотрудников. Скрытая или непроверенная кухня в районе не показывается.',
  adminKitchens: 'Кухни',
  adminOrders: 'Заказы',
  adminTickets: 'Жалобы',
  adminUsers: 'Люди',
  adminSearch: 'Найти заказ',
  adminSearchHint: 'Телефон, имя или номер заказа',
  adminNoOrders: 'Ничего не найдено.',
  adminForceCancel: 'Отменить заказ',
  adminHide: 'Скрыть',
  adminShow: 'Показать',
  adminVerify: 'Подтвердить',
  adminReject: 'Отклонить',
  adminBlock: 'Заблокировать',
  adminUnblock: 'Разблокировать',
  kitchenHidden: 'Кухня скрыта',
  kitchenHiddenHint: 'Поддержка убрала эту кухню из списка. Выбери другую в районе.',
  kitchenPending: 'Кухня на проверке. В районе её пока не видно.',
  kitchenRejected: 'Заявку отклонили',
  loginTitle: 'Вход',
  registerTitle: 'Регистрация',
  loginHint: 'Почта и пароль. Без SMS.',
  registerHint: 'Один аккаунт: и покупатель, и пекарь.',
  noAccount: 'Нет аккаунта? Зарегистрируйся',
  hasAccount: 'Уже есть аккаунт? Войти',
  logout: 'Выйти',
  accountTitle: 'Кабинет',
  roleSwitch: 'Режим',
  roleSwitchHint: 'Один аккаунт. Покупай как гость или готовь как пекарь.',
  blockedTitle: 'Аккаунт заблокирован',
  report: 'Пожаловаться',
  reportTitle: 'Жалоба в поддержку',
  reportHint: 'Опиши проблему. Поддержка может скрыть кухню или заблокировать человека.',
  reportSent: 'Жалоба отправлена',
  reportBody: 'Что случилось',
  topic: 'Тема',
  topics: {
    late: 'Опоздание',
    quality: 'Качество еды',
    fake_kitchen: 'Липовая кухня',
    rude: 'Грубость',
    other: 'Другое',
  },
  save: 'Сохранить',
  language: 'Язык',
  authError: 'Неверная почта или пароль',
  existsError: 'Эта почта уже зарегистрирована',
  loginNotFoundError: 'Неверная почта или пароль',
  loginPasswordError: 'Неверная почта или пароль',
  passwordHint: 'Не меньше 8 символов',
  emailError: 'Проверь почту — нужен вид name@mail.com',
  dbError: 'База не подключена. На Vercel нужен DATABASE_URL (Neon) и Redeploy.',
  serverError: 'API упал. Залей этот код, поставь JWT_SECRET, Redeploy, затем зарегистрируйся на живом сайте.',
  apiMissingError: 'Маршрут API не найден. Сделайте Redeploy проекта.',
  networkError: 'Нет связи с сервером.',
  healthBanner: 'База не отвечает. {hint}',
  nextStatus: 'Следующий статус',
  verifyHint: 'Проверь адрес и имя, затем подтверди кухню.',
  rejectNote: 'Причина отказа',
  blockReason: 'Причина блокировки',
  blockReasonRequired: 'Сначала напиши причину блокировки.',
  pendingShort: 'На проверке',
  verifiedShort: 'Ок',
  rejectedShort: 'Отказ',
  hiddenShort: 'Скрыта',
  tomorrow: 'завтра',
  dayAfter: 'послезавтра',
  adminVerified: 'Кухня подтверждена',
  adminRejected: 'Заявку отклонили',
  adminHidden: 'Кухня скрыта из района',
  adminShown: 'Кухня снова в районе',
  adminBlocked: 'Пользователь заблокирован',
  adminUnblocked: 'Пользователь разблокирован',
  adminCancelled: 'Заказ отменён',
  adminTicketUpdated: 'Статус жалобы обновлён',
  adminActionFailed: 'Не получилось. Попробуй ещё раз.',
  adminFieldsError: 'Заполни обязательные поля.',
  adminEmptyKitchens: 'Заявок на кухни пока нет.',
  adminEmptyUsers: 'Пользователей пока нет.',
  adminEmptyTickets: 'Жалоб пока нет.',
  adminOrdersHint: 'Новый заказ уже в статусе «принят». Пекарь ведёт его дальше. Поддержка может только отменить.',
};
